# Build stage
FROM node:20-alpine AS builder

WORKDIR /app

ARG VITE_API_URL

# Copy root package files
COPY package*.json ./
COPY apps/web ./apps/web

# Install dependencies
RUN npm ci

ENV VITE_API_URL=$VITE_API_URL
# Build web app
RUN npm run build -w @andpayments/web

# Production stage
FROM node:20-alpine

WORKDIR /app

# Install serve to run the static app
RUN npm install -g serve

# Copy built application from builder
COPY --from=builder /app/apps/web/dist ./dist

EXPOSE 3001

CMD ["serve", "-s", "dist", "-l", "3001"]
